// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: anime_studios.sql

package queries

import (
	"context"
)

const createAnimeStudio = `-- name: CreateAnimeStudio :one
INSERT INTO anime_studios (anime_id, studio_id)
VALUES (?, ?)
RETURNING anime_id, studio_id
`

type CreateAnimeStudioParams struct {
	AnimeID  int64
	StudioID int64
}

func (q *Queries) CreateAnimeStudio(ctx context.Context, arg CreateAnimeStudioParams) (AnimeStudio, error) {
	row := q.db.QueryRowContext(ctx, createAnimeStudio, arg.AnimeID, arg.StudioID)
	var i AnimeStudio
	err := row.Scan(&i.AnimeID, &i.StudioID)
	return i, err
}
