// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: genres.sql

package queries

import (
	"context"
)

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (name)
VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, createGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genres
WHERE id = ?
`

func (q *Queries) DeleteGenre(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGenre, id)
	return err
}

const findGenre = `-- name: FindGenre :one
SELECT id, name FROM genres
WHERE name = ?
`

func (q *Queries) FindGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, findGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenre = `-- name: GetGenre :one
SELECT id, name FROM genres
WHERE id = ?
`

func (q *Queries) GetGenre(ctx context.Context, id int64) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenre, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateGenre = `-- name: UpdateGenre :one
UPDATE genres
SET name = ?
WHERE id = ?
RETURNING id, name
`

type UpdateGenreParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) (Genre, error) {
	row := q.db.QueryRowContext(ctx, updateGenre, arg.Name, arg.ID)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
