// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"
)

type Anime struct {
	ID           int32
	IDAl         int32
	TitleRomaji  string
	TitleNative  sql.NullString
	TitleEnglish sql.NullString
	Format       string
	Status       string
	Description  string
	StartDate    time.Time
	EndDate      time.Time
	Season       string
	SeasonYear   sql.NullInt16
	Episodes     int16
	Duration     int16
	BannerImage  sql.NullString
	StImage      string
}

type AnimeGenre struct {
	AnimeID int32
	GenreID int32
}

type AnimeStudio struct {
	AnimeID  int32
	StudioID int32
}

type CoverImage struct {
	ID         int32
	AnimeID    int32
	ExtraLarge sql.NullString
	Large      sql.NullString
	Medium     sql.NullString
	Color      sql.NullString
}

type Genre struct {
	ID   int32
	Name string
}

type Studio struct {
	ID   int32
	Name string
}

type Synonym struct {
	ID      int32
	AnimeID int32
	Name    string
}
